
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractInstanceWithAddress, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import XmasLetterboxContractArtifactJson from '../../target/xmas_letters-XmasLetterbox.json' with { type: 'json' };
export const XmasLetterboxContractArtifact = loadContractArtifact(XmasLetterboxContractArtifactJson as NoirCompiledContract);


      export type XmasLetter = {
        message: FieldLike
      }
    

/**
 * Type-safe interface for contract XmasLetterbox;
 */
export class XmasLetterboxContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, XmasLetterboxContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, XmasLetterboxContract.artifact, wallet) as Promise<XmasLetterboxContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, ) {
    return new DeployMethod<XmasLetterboxContract>(PublicKeys.default(), wallet, XmasLetterboxContractArtifact, XmasLetterboxContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, ) {
    return new DeployMethod<XmasLetterboxContract>(publicKeys, wallet, XmasLetterboxContractArtifact, XmasLetterboxContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof XmasLetterboxContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<XmasLetterboxContract['methods'][M]>
  ) {
    return new DeployMethod<XmasLetterboxContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      XmasLetterboxContractArtifact,
      XmasLetterboxContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return XmasLetterboxContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(XmasLetterboxContractArtifactJson as NoirCompiledContract);
  }
  

  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** send_letter(to: struct, message: field) */
    send_letter: ((to: AztecAddressLike, message: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
    public static get events(): { XmasLetter: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] } } {
    return {
      XmasLetter: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "message",
            "type": {
                "kind": "field"
            }
        }
    ],
    "path": "XmasLetterbox::XmasLetter"
},
        eventSelector: EventSelector.fromString("0x632aeea9"),
        fieldNames: ["message"],
      }
    };
  }
  
}
